Added more functionality

diff --git a/lib/npm b/lib/npm
--- a/lib/npm
+++ b/lib/npm
@@ -1,1 +1,21 @@
 #!/usr/bin/env bash
+
+run_npm() {
+    # Check for npm
+    if type_exists 'npm'; then
+        e_header "Installing Node.js packages..."
+
+        # List of npm packages
+        local packages="jshint yo grunt gulp bower"
+
+        # Install packages globally and quietly
+        npm install $packages --global --quiet
+
+        [[ $? ]] && e_success "Done"
+    else
+        printf "\n"
+        e_error "Error: npm not found."
+        printf "Aborting...\n"
+        exit
+    fi
+}
